geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = "authapp"

urlpatterns = [
    path("login/", authapp.login, name="login"),
    path("register/", authapp.register, name="register"),
    path("edit/", authapp.edit, name="edit"),
    path("logout/", authapp.logout, name="logout"),
    path("verify/<str:email>/<str:key>", authapp.verify, name="verify"),
]

geekshop/basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = "basketapp"

urlpatterns = [
    path("", basketapp.view, name="view"),
    path("add/<int:product_id>/", basketapp.add, name="add"),
    path("remove/<int:basket_id>/", basketapp.remove, name="remove"),
    path("edit/<int:basket_id>/<int:quantity>/", basketapp.edit, name="edit"),
]

geekshop/geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from mainapp import views as mainapp

urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path("social/", include("social_django.urls", namespace="social")),
    path("admin/", include("adminapp.urls", namespace="admin")),
    path("auth/", include("authapp.urls", namespace="auth")),
    path("basket/", include("basketapp.urls", namespace="basket")),
    path("orders/", include("ordersapp.urls", namespace="orders")),
    path("", mainapp.index, name="index"),
    path("contact", mainapp.contact, name="contact"),
    path("products/", mainapp.products, name="products"),
    path("products/<int:pk>/", mainapp.category, name="category"),
    path("products/<int:pk>/<int:page>/", mainapp.category, name="category"),
    path("product/<int:pk>/", mainapp.product, name="product"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/ordersapp/urls.py
from django.urls import path

import ordersapp.views as ordersapp

app_name = "ordersapp"


urlpatterns = [
    path("", ordersapp.OrderListView.as_view(), name="list"),
    path("create", ordersapp.create_order, name="create"),
    path("<int:pk>", ordersapp.OrderUpdateView.as_view(), name="update"),
    path("<int:pk>/pay", ordersapp.pay_for_order, name="pay"),
    path("<int:pk>/cancel", ordersapp.cancel_order, name="cancel"),
]

geekshop/basketapp/models.py
from django.contrib.auth import get_user_model
from django.db import models

from mainapp.models import Product


class BasketManager(models.Manager):
    def quantity(self):
        return sum(item.quantity for item in self.all())

    def sum(self):
        return sum(item.product.price * item.quantity for item in self.all())
    
    def can_create_order(self):
        return all(item.quantity <= item.product.quantity for item in self.all())


class Basket(models.Model):
    user = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name="basket"
    )
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = BasketManager()

    @property
    def cost(self):
        return self.quantity * self.product.price

    def __str__(self):
        return f"{self.product} - {self.quantity} шт"

geekshop/basketapp/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseBadRequest
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from mainapp.models import Product

from .models import Basket


@login_required
def view(request):
    return render(request, "basketapp/view.html", context={"title": "Корзина"})


@login_required
def add(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    basket = Basket.objects.filter(user=request.user, product=product)
    if basket:
        basket_item = basket[0]
        basket_item.quantity += 1
    else:
        basket_item = Basket(user=request.user, product=product)

    if basket_item.quantity <= product.quantity:
        basket_item.save()

    if "next" in request.META.get("HTTP_REFERER"):
        redirect_url = reverse("index")
    else:
        redirect_url = request.META.get("HTTP_REFERER", reverse("index"))    

    return HttpResponseRedirect(redirect_url)


@login_required
def remove(request, basket_id):
    basket = get_object_or_404(Basket, pk=basket_id)
    basket.quantity -= 1
    if not basket.quantity:
        basket.delete()
    else:
        basket.save()
    return HttpResponseRedirect(reverse("basket:view"))


@login_required
def edit(request, basket_id, quantity):
    basket = get_object_or_404(Basket, pk=basket_id)
    basket.quantity = quantity
    if not basket.quantity:
        basket.delete()
    else:
        basket.save()
    return render(request, "basketapp/includes/inc_basket_list.html")

geekshop/basketapp/templates/basketapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <title>
            {% block title %}
            {{ title }}
            {% endblock %}
        </title>
        {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'pure-min.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'basket-styles.css' %}"/>
        {% endblock %}
        {% block js %}
        <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'js/basket_scripts.js' %}"></script>
        {% endblock %}
    </head>
    <body>
        <div class="content">
            <a class="pure-button button-secondary" href="{% url 'index' %}"><- На сайт</a></h4>
            <h2>{{ title }}</h2>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

geekshop/basketapp/templates/basketapp/view.html
{% extends 'basketapp/base.html' %}
{% load static %}
{% block content %}
<div class="basket_list">
    {% include 'basketapp/includes/inc_basket_list.html' %}
    {% if basket.quantity %}
    <div class="create-button">
        <a href="{% url 'orders:create' %}"
           class="pure-button
                  pure-button-primary
                  {% if not user.basket.can_create_order %}
                  pure-button-disabled
                  {% endif %}">
            Создать заказ
        </a>
    </div>
    {% endif %}
</div>
{% endblock %}