geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = "authapp"

urlpatterns = [
    path("login/", authapp.login, name="login"),
    path("register/", authapp.register, name="register"),
    path("edit/", authapp.edit, name="edit"),
    path("logout/", authapp.logout, name="logout"),
    path("verify/<str:email>/<str:key>", authapp.verify, name="verify"),
]

geekshop/geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from mainapp import views as mainapp

urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path("social/", include("social_django.urls", namespace="social")),
    path("admin/", include("adminapp.urls", namespace="admin")),
    path("auth/", include("authapp.urls", namespace="auth")),
    path("basket/", include("basketapp.urls", namespace="basket")),
    path("orders/", include("ordersapp.urls", namespace="orders")),
    path("", mainapp.index, name="index"),
    path("contact", mainapp.contact, name="contact"),
    path("products/", mainapp.products, name="products"),
    path("products/<int:pk>/", mainapp.category, name="category"),
    path("products/<int:pk>/<int:page>/", mainapp.category, name="category"),
    path("product/<int:pk>/", mainapp.product, name="product"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/ordersapp/urls.py
from django.urls import path

import ordersapp.views as ordersapp

app_name = "ordersapp"


urlpatterns = [
    path("", ordersapp.OrderListView.as_view(), name="list"),
    path("create", ordersapp.create_order, name="create"),
    path("<int:pk>", ordersapp.OrderUpdateView.as_view(), name="update"),
    path("<int:pk>/pay", ordersapp.pay_for_order, name="pay"),
    path("<int:pk>/cancel", ordersapp.cancel_order, name="cancel"),
]

geekshop/ordersapp/models.py
from django.contrib.auth import get_user_model
from django.db import models, transaction
from django.dispatch import receiver
from django.db.models.signals import pre_save

from mainapp.models import Product


class Order(models.Model):
    CREATED = "CREATED"
    PAID = "PAID"
    SENT = "SENT"
    DELIVERED = "DELIVERED"
    CANCELED = "CANCELED"

    STATUS_CHOICES = [
        (CREATED, "Создан"),
        (PAID, "Оплачен"),
        (SENT, "Отправлен"),
        (DELIVERED, "Доставлен"),
        (CANCELED, "Отменён"),
    ]

    user = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name="orders"
    )
    status = models.CharField(max_length=16, choices=STATUS_CHOICES, default=CREATED)
    created_at = models.DateTimeField(auto_now_add=True)

    @property
    def can_pay(self):
        return self.status == Order.CREATED

    @property
    def can_cancel(self):
        return self.status in [Order.CREATED, Order.PAID, Order.SENT]


class OrderItemManager(models.Manager):
    def quantity(self):
        return sum(item.quantity for item in self.all())

    def sum(self):
        return sum(item.product.price * item.quantity for item in self.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="items")
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=1)

    objects = OrderItemManager()

    @property
    def cost(self):
        return self.quantity * self.product.price

    def __str__(self):
        return f"{self.product} - {self.quantity} шт"
    


@receiver(pre_save, sender=OrderItem)
def update_product_quantity(sender, instance, **kwargs):
    old_order_item = OrderItem.objects.filter(pk=instance.pk).first()
    if old_order_item:
        quantity_delta = instance.quantity - old_order_item.quantity
        instance.product.quantity -= quantity_delta
    else:
        instance.product.quantity -= instance.quantity

    instance.product.save()

geekshop/ordersapp/forms.py
from django import forms

from .models import Order, OrderItem


class OrderItemForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        exclude = ("order",)

    product_price = forms.DecimalField(required=False, disabled=True)
    summary = forms.DecimalField(required=False, disabled=True)

OrderItemFormset = forms.inlineformset_factory(Order, OrderItem, OrderItemForm, extra=0)

geekshop/ordersapp/views.py
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.http import HttpResponseBadRequest, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, UpdateView

from ordersapp.forms import OrderItemFormset
from ordersapp.models import Order, OrderItem
from utils.mixins import LoginRequiredMixin, TitleMixin


# Create your views here.
class OrderListView(LoginRequiredMixin, TitleMixin, ListView):
    template_name = "ordersapp/order_list.html"
    model = Order
    title = "Заказы"

    def get_queryset(self):
        return Order.objects.order_by("created_at")


@login_required
@transaction.atomic
def create_order(request):
    basket = request.user.basket
    basket_items = basket.all()
    if not basket_items or not basket.can_create_order():
        return HttpResponseBadRequest()

    order = Order(user=request.user)
    order.save()
    for item in basket_items:
        item = OrderItem(order=order, product=item.product, quantity=item.quantity)
        item.save()

    basket_items.delete()
    return HttpResponseRedirect(reverse("orders:list"))


@login_required
def pay_for_order(request, pk):
    order = get_object_or_404(Order, pk=pk)
    if not order.can_pay:
        return HttpResponseBadRequest()

    order.status = Order.PAID
    order.save()
    return HttpResponseRedirect(reverse("orders:list"))


@login_required
@transaction.atomic
def cancel_order(request, pk):
    order = get_object_or_404(Order, pk=pk)
    if not order.can_cancel:
        return HttpResponseBadRequest()

    order.status = Order.CANCELED
    order.save()
    return HttpResponseRedirect(reverse("orders:list"))


class OrderUpdateView(LoginRequiredMixin, TitleMixin, UpdateView):
    template_name = "ordersapp/order_update.html"
    model = Order
    success_url = reverse_lazy("orders:list")
    title = "Редактирование заказа"
    fields = ()

    def get_context_data(self, **kwargs):
        formset = kwargs.get("formset", OrderItemFormset(instance=self.object))
        context = super().get_context_data(**kwargs)

        context["orderitems"] = formset
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        formset = OrderItemFormset(self.request.POST, instance=self.object)
        if form.is_valid() and formset.is_valid():
            return self.form_valid(form, formset)
        else:
            return self.form_invalid(form, formset)

    @transaction.atomic
    def form_valid(self, form, formset):
        self.object = form.save()
        formset.save()
        return super().form_valid(form)

    def form_invalid(self, form, formset):
        return self.render_to_response(
            self.get_context_data(form=form, formset=formset)
        )

geekshop/ordersapp/templates/ordersapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <title>
            {% block title %}
            {{ title }}
            {% endblock %}
        </title>
        {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'pure-min.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'orders-styles.css' %}"/>
        <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'js/jquery.formset.js' %}"></script>
        {% endblock %}
        {% block js %}
        {% endblock %}
    </head>
    <body>
        <div class="content">
            <a class="pure-button button-secondary" href="{% url 'index' %}"><- На сайт</a></h4>
            <h2>{{ title }}</h2>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

geekshop/ordersapp/templates/ordersapp/order_list.html
{% extends 'ordersapp/base.html' %}
{% load static %}
{% block content %}
{% if not object_list %}
    <h4>У вас нет активных заказов</h4>
{% else %}
    <table class="pure-table">
        <thead>
            <tr>
                <th>Created at</th>
                <th>Status</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
            <tr>
                <td>{{ object.created_at|date:"d/m/Y H:i:s" }}</td>
                <td>{{ object.get_status_display }}</td>
                <td>
                    <a href="{% url 'orders:update' object.pk %}" class="pure-button pure-button-primary">
                        редактировать
                    </a>
                </td>
                <td>
                    {% if object.can_pay %}
                        <a href="{% url 'orders:pay' object.pk %}" class="pure-button pure-button-primary">
                            оплатить
                        </a>
                    {% else %}
                        <span>Оплачен</span>
                    {% endif %}
                </td>
                <td>
                    {% if object.can_cancel %}
                        <a href="{% url 'orders:cancel' object.pk %}" class="pure-button pure-button-primary">
                            отменить
                        </a>
                    {% else %}
                        <span>Отменён</span>
                    {% endif %}                    
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endif %}
{% endblock %}

geekshop/ordersapp/templates/ordersapp/order_update.html
{% extends 'ordersapp/base.html' %}

{% block js %}
<script type="text/javascript">
    $(function() {
        $('#order-form fieldset').formset({
            'addText': 'Добавить',
            'deleteText': 'Удалить',
            'addCssClass': 'pure-button pure-button-primary',
            'deleteCssClass': 'pure-button pure-button-primary',
        })
    })
</script>
{% endblock %}

{% block content %}
<form id="order-form" class="pure-form" action="{% url 'orders:update' object.pk %}" method="post">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}

    {{ orderitems.management_form }}
    {% for item_form in orderitems %}
        <fieldset>
        {% for field in item_form %}
            {% if field.name == 'product_price' or field.name == 'summary' %}
                {% if field.value != None %}
                    <span></span>
                    <span>{{ field.value }}</span> 
                {% endif %}
            {% else %}
                {% if not field.is_hidden %}
                    <span>{{ field.label }}:</span>
                {% endif %}
                {{ field }}
            {% endif %}
        {% endfor %}
        </fieldset>
    {% endfor %}
    <input class="pure-button pure-button-primary" type="submit" value="Сохранить">
</form>
{% endblock %}