geekshop/adminapp/urls.py
from django.urls import path

import adminapp.views as adminapp

app_name = "adminapp"


urlpatterns = [
    path("users/", adminapp.UserListView.as_view(), name="users"),
    path("users/create/", adminapp.UserCreateView.as_view(), name="create_user"),
    path(
        "users/update/<int:pk>", adminapp.UserUpdateView.as_view(), name="update_user"
    ),
    path("users/delete/<int:pk>", adminapp.delete_user, name="delete_user"),
    path("categories/", adminapp.CategoryListView.as_view(), name="categories"),
    path("categories/create/", adminapp.create_category, name="create_category"),
    path(
        "categories/update/<int:pk>", adminapp.update_category, name="update_category"
    ),
    path(
        "categories/delete/<int:pk>", adminapp.delete_category, name="delete_category"
    ),
    path("products/<int:category_pk>", adminapp.products, name="products"),
    path(
        "products/<int:category_pk>/create/",
        adminapp.create_product,
        name="create_product",
    ),
    path(
        "products/update/<int:product_pk>/",
        adminapp.update_product,
        name="update_product",
    ),
    path(
        "products/delete/<int:product_pk>/",
        adminapp.delete_product,
        name="delete_product",
    ),
]

geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = "authapp"

urlpatterns = [
    path("login/", authapp.login, name="login"),
    path("register/", authapp.register, name="register"),
    path("edit/", authapp.edit, name="edit"),
    path("logout/", authapp.logout, name="logout"),
    path("verify/<str:email>/<str:key>", authapp.verify, name="verify"),
]

geekshop/basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = "basketapp"

urlpatterns = [
    path("", basketapp.view, name="view"),
    path("add/<int:product_id>/", basketapp.add, name="add"),
    path("remove/<int:basket_id>/", basketapp.remove, name="remove"),
    path("edit/<int:basket_id>/<int:quantity>/", basketapp.edit, name="edit"),
]

geekshop/geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from mainapp import views as mainapp

urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path("social/", include("social_django.urls", namespace="social")),
    path("admin/", include("adminapp.urls", namespace="admin")),
    path("auth/", include("authapp.urls", namespace="auth")),
    path("basket/", include("basketapp.urls", namespace="basket")),
    path("orders/", include("ordersapp.urls", namespace="orders")),
    path("", mainapp.index, name="index"),
    path("contact", mainapp.contact, name="contact"),
    path("products/", mainapp.products, name="products"),
    path("products/<int:pk>/", mainapp.category, name="category"),
    path("products/<int:pk>/<int:page>/", mainapp.category, name="category"),
    path("product/<int:pk>/", mainapp.product, name="product"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/ordersapp/urls.py
from django.urls import path

import ordersapp.views as ordersapp

app_name = "ordersapp"


urlpatterns = [
    path("", ordersapp.OrderListView.as_view(), name="list"),
    path("create", ordersapp.create_order, name="create"),
    path("<int:pk>", ordersapp.OrderUpdateView.as_view(), name="update"),
    path("<int:pk>/pay", ordersapp.pay_for_order, name="pay"),
    path("<int:pk>/cancel", ordersapp.cancel_order, name="cancel"),
]

geekshop/mainapp/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=32, unique=True)
    description = models.CharField(max_length=140)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.id}: {self.name}"


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=32)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to="product_images")
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(default=0)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.id}: {self.name}"

    def can_add_to_basket(self, user):
        pass

geekshop/mainapp/views.py
import random

from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .models import Category, Product


def index(request):
    return render(
        request,
        "mainapp/index.html",
        context={"title": "Главная"},
    )


def products(request):
    categories = Category.objects.all()
    products = Product.objects.all()
    hot_product = random.choice(products)
    products = products.exclude(pk=hot_product.pk)[:3]
    return render(
        request,
        "mainapp/products.html",
        context={
            "title": "Продукты",
            "hot_product": hot_product,
            "products": products,
            "categories": categories,
        },
    )


def product(request, pk):
    categories = Category.objects.all()
    product = get_object_or_404(Product, pk=pk)
    return render(
        request,
        "mainapp/product.html",
        context={
            "title": product.name,
            "product": product,
            "category": product.category,
            "categories": categories,
        },
    )


def category(request, pk, page=1):
    categories = Category.objects.all()
    category = get_object_or_404(Category, id=pk)
    products = Product.objects.filter(category=category).order_by("price")
    paginator = Paginator(products, per_page=3)

    if page > paginator.num_pages:
        return HttpResponseRedirect(reverse("category", args=[category.id]))

    return render(
        request,
        "mainapp/category.html",
        context={
            "title": "Продукты",
            "products": paginator.page(page),
            "category": category,
            "categories": categories,
        },
    )


def contact(request):
    return render(
        request,
        "mainapp/contact.html",
        context={
            "title": "Контакты",
        },
    )

geekshop/mainapp/templates/mainapp/includes/categories_menu_inc.html
<ul class="links-menu">
    {% with url_name=request.resolver_match.url_name %}
    {% with category_id=request.resolver_match.kwargs.pk %}
    <li><a href="{% url 'products' %}" class="{% if url_name == 'products' %}active{% endif %}">все</a></li>
    {% for category in categories %}
        <li><a href="{% url 'category' category.id %}" class="{% if url_name == 'category' and category_id == category.id %}active{% endif %}">{{ category.name }}</a></li>
    {% endfor %}
    {% endwith %}
    {% endwith %}
</ul>

geekshop/mainapp/templates/mainapp/includes/main_menu_inc.html
<div class="header clearfix">
    <a href="{% url 'index' %}" class="logo"></a>
    <ul class="menu">
        {% with url_name=request.resolver_match.url_name %}
        {% for link, name in menu.items %}
        <li><a href="{% url link %}" class="{% if url_name == link %} active {% endif %}">{{ name }}</a></li>
        {% endfor %}
        {% endwith %}
        {% if request.user.is_authenticated %}
            <li>
                <div class="dropdown">
                    <a href="#">{{ user.username }}</a>
                    <div class="dropdown-content">
                        <a href="{% url 'auth:edit' %}">Профиль</a>
                        <a href="{% url 'basket:view' %}">Корзина&nbsp;({{ basket.quantity }})</a>
                        <a href="{% url 'orders:list' %}">Заказы</a>
                    </div>
                </div>
            </li>
            {% if request.user.is_superuser %}
            <li><a href="{% url 'admin:users' %}">Админка</a></li>
            {% endif %}
            <li><a href="{% url 'auth:logout' %}">Выйти</a></li>
        {% else %}
            <li><a href="{% url 'auth:login' %}">Войти</a></li>
            <li><a href="{% url 'auth:register' %}">Регистрация</a></li>
        {% endif %}
    </ul>
    <a href="#" class="search"></a>
</div>

geekshop/mainapp/templates/mainapp/includes/product_list_inc.html
{% load static %}

{% for product in products %}
<div class="block">
    <a href="{% url 'product' product.id %}">
        {% if product.image %}
            <img class="product-image" src="{{ product.image.url }}" alt="">
        {% else %}
            <img class="product-image" src="{% static 'img/product-1.jpg' %}" alt="">
        {% endif %}
        <div class="text">
            <img src="/static/img/icon-hover.png" alt="img">
            <h4>{{ product.name|title }}</h4>
            <p>{{ product.description|upper|truncatewords:10 }}</p>
        </div>
    </a>
</div>
{% endfor %}