geekshop/adminapp/urls.py
from django.urls import path

import adminapp.views as adminapp

app_name = "adminapp"


urlpatterns = [
    path("users/", adminapp.UserListView.as_view(), name="users"),
    path("users/create/", adminapp.UserCreateView.as_view(), name="create_user"),
    path(
        "users/update/<int:pk>", adminapp.UserUpdateView.as_view(), name="update_user"
    ),
    path("users/delete/<int:pk>", adminapp.delete_user, name="delete_user"),
    path("categories/", adminapp.CategoryListView.as_view(), name="categories"),
    path("categories/create/", adminapp.create_category, name="create_category"),
    path(
        "categories/update/<int:pk>", adminapp.update_category, name="update_category"
    ),
    path(
        "categories/delete/<int:pk>", adminapp.delete_category, name="delete_category"
    ),
    path("products/<int:category_pk>", adminapp.products, name="products"),
    path(
        "products/<int:category_pk>/create/",
        adminapp.create_product,
        name="create_product",
    ),
    path(
        "products/update/<int:product_pk>/",
        adminapp.update_product,
        name="update_product",
    ),
    path(
        "products/delete/<int:product_pk>/",
        adminapp.delete_product,
        name="delete_product",
    ),
]

geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = "authapp"

urlpatterns = [
    path("login/", authapp.login, name="login"),
    path("register/", authapp.register, name="register"),
    path("edit/", authapp.edit, name="edit"),
    path("logout/", authapp.logout, name="logout"),
    path("verify/<str:email>/<str:key>", authapp.verify, name="verify"),
]

geekshop/geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from mainapp import views as mainapp

urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path("social/", include("social_django.urls", namespace="social")),
    path("admin/", include("adminapp.urls", namespace="admin")),
    path("auth/", include("authapp.urls", namespace="auth")),
    path("basket/", include("basketapp.urls", namespace="basket")),
    path("orders/", include("ordersapp.urls", namespace="orders")),
    path("", mainapp.index, name="index"),
    path("contact", mainapp.contact, name="contact"),
    path("products/", mainapp.products, name="products"),
    path("products/<int:pk>/", mainapp.category, name="category"),
    path("products/<int:pk>/<int:page>/", mainapp.category, name="category"),
    path("product/<int:pk>/", mainapp.product, name="product"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/adminapp/models.py
from django.db import models

# Create your models here.

geekshop/adminapp/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.forms.widgets import HiddenInput

from authapp.models import ShopUser
from mainapp.models import Category, Product


class RegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ("username",)


class UserEditForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ("username", "first_name", "last_name", "image", "email", "city")


class CategoryEditForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = "__all__"


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["category"].widget = HiddenInput()

geekshop/adminapp/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView

from adminapp.forms import (CategoryEditForm, ProductEditForm, RegisterForm,
                            UserEditForm)
from authapp.models import ShopUser
from mainapp.models import Category, Product
from utils.decorators import check_is_superuser
from utils.mixins import SuperuserRequiredMixin, TitleMixin


class UserListView(SuperuserRequiredMixin, TitleMixin, ListView):
    template_name = "adminapp/users.html"
    model = ShopUser
    title = "Пользователи"
    paginate_by = 4
    page_kwarg = "my_page"

    def get_queryset(self):
        return ShopUser.objects.order_by("date_joined")


class UserCreateView(SuperuserRequiredMixin, TitleMixin, CreateView):
    template_name = "adminapp/create_user.html"
    model = ShopUser
    form_class = RegisterForm
    success_url = reverse_lazy("admin:users")
    title = "Создание пользователя"


class UserUpdateView(SuperuserRequiredMixin, TitleMixin, UpdateView):
    template_name = "adminapp/update_user.html"
    model = ShopUser
    form_class = UserEditForm
    success_url = reverse_lazy("admin:users")
    title = "Редактирование пользователя"


@check_is_superuser
def delete_user(request, pk):
    user = get_object_or_404(ShopUser, pk=pk)
    user.is_active = False
    user.save()
    return HttpResponseRedirect(reverse("admin:users"))


class CategoryListView(SuperuserRequiredMixin, TitleMixin, ListView):
    template_name = "adminapp/categories.html"
    model = Category
    title = "Категории"


@check_is_superuser
def create_category(request):
    form = CategoryEditForm()
    if request.method == "POST":
        form = CategoryEditForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("admin:categories"))

    return render(
        request,
        "adminapp/create_category.html",
        context={"title": "Создание категории", "form": form},
    )


@check_is_superuser
def update_category(request, pk):
    category = get_object_or_404(Category, pk=pk)
    form = CategoryEditForm(instance=category)
    if request.method == "POST":
        form = CategoryEditForm(instance=category, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("admin:categories"))

    return render(
        request,
        "adminapp/update_category.html",
        context={
            "title": "Редактирование категории",
            "category": category,
            "form": form,
        },
    )


@check_is_superuser
def delete_category(request, pk):
    category = get_object_or_404(Category, pk=pk)
    category.is_active = False
    category.save()
    return HttpResponseRedirect(reverse("admin:categories"))


@check_is_superuser
def products(request, category_pk):
    category = get_object_or_404(Category, pk=category_pk)
    return render(
        request,
        "adminapp/products.html",
        context={
            "title": f"Категория: {category.name}",
            "products": Product.objects.filter(category=category),
            "category": category,
        },
    )


@check_is_superuser
def create_product(request, category_pk):
    category = get_object_or_404(Category, pk=category_pk)
    form = ProductEditForm(initial={"category": category})
    if request.method == "POST":
        form = ProductEditForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("admin:products", args=[category_pk]))

    return render(
        request,
        "adminapp/create_product.html",
        context={"title": "Создание продукта", "category": category, "form": form},
    )


@check_is_superuser
def update_product(request, product_pk):
    product = get_object_or_404(Product, pk=product_pk)
    form = ProductEditForm(instance=product)
    if request.method == "POST":
        form = ProductEditForm(instance=product, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(
                reverse("admin:products", args=[product.category.pk])
            )

    return render(
        request,
        "adminapp/update_product.html",
        context={"title": "Редактирование категории", "product": product, "form": form},
    )


@check_is_superuser
def delete_product(request, product_pk):
    product = get_object_or_404(Product, pk=product_pk)
    product.is_active = False
    product.save()
    return HttpResponseRedirect(reverse("admin:products", args=[product.category.pk]))

geekshop/adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <title>
            {% block title %}
            {{ title }}
            {% endblock %}
        </title>
        {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'pure-min.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'admin-styles.css' %}"/>
        {% endblock %}
        {% block js %}
        {% endblock %}
    </head>
    <body>
        <div class="content">
            <a class="pure-button button-secondary" href="{% url 'index' %}"><- На сайт</a>
            <a class="pure-button button-secondary" href="{% url 'admin:users' %}">Пользователи</a>
            <a class="pure-button button-secondary" href="{% url 'admin:categories' %}">Категории</a>
            <h2>{{ title }}</h2>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

geekshop/adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}

{% block content %}
<div class="create-button">
    <a href="{% url 'admin:create_category' %}" class="pure-button pure-button-primary">
        Создать категорию
    </a>
</div>
<table class="pure-table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for category in object_list %}
        <tr class="{% if not category.is_active %} inactive {% endif %}">
            <td>{{ category.name }}</td>
            <td>{{ category.description }}</td>
            <td>
                <a href="{% url 'admin:products' category.pk %}" class="pure-button pure-button-primary">
                    к товарам категории
                </a>
            </td>
            <td>
                <a href="{% url 'admin:update_category' category.pk %}" class="pure-button pure-button-primary">
                    редактировать
                </a>
            </td>
            <td>
                <a href="{% url 'admin:delete_category' category.pk %}" class="pure-button pure-button-primary">
                    удалить
                </a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

geekshop/adminapp/templates/adminapp/create_category.html
{% extends 'adminapp/base.html' %}

{% block content %}
<form class="pure-form" action="{% url 'admin:create_category' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="pure-button pure-button-primary" type="submit" value="Создать категорию">
</form>
{% endblock %}

geekshop/adminapp/templates/adminapp/create_product.html
{% extends 'adminapp/base.html' %}

{% block content %}
<form class="pure-form" enctype='multipart/form-data' action="{% url 'admin:create_product' category.pk %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="pure-button pure-button-primary" type="submit" value="Создать продукт">
</form>
{% endblock %}

geekshop/adminapp/templates/adminapp/create_user.html
{% extends 'adminapp/base.html' %}

{% block content %}
<form class="pure-form" action="{% url 'admin:create_user' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="pure-button pure-button-primary" type="submit" value="Создать пользователя">
</form>
{% endblock %}

geekshop/adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% block content %}
<div class="create-button">
    <a href="{% url 'admin:create_product' category.pk %}" class="pure-button pure-button-primary">
        Создать продукт
    </a>
</div>
<table class="pure-table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Quantity</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for product in products %}
        <tr class="{% if not product.is_active %} inactive {% endif %}">
            <td>{{ product.name }}</td>
            <td>{{ product.description }}</td>
            <td>{{ product.quantity }}</td>
            <td>
                <a href="{% url 'admin:update_product' product.pk %}" class="pure-button pure-button-primary">
                    редактировать
                </a>
            </td>
            <td>
                <a href="{% url 'admin:delete_product' product.pk %}" class="pure-button pure-button-primary">
                    удалить
                </a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

geekshop/adminapp/templates/adminapp/update_category.html
{% extends 'adminapp/base.html' %}

{% block content %}
<form class="pure-form" action="{% url 'admin:update_category' category.pk %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="pure-button pure-button-primary" type="submit" value="Сохранить">
</form>
{% endblock %}

geekshop/adminapp/templates/adminapp/update_product.html
{% extends 'adminapp/base.html' %}

{% block content %}
<form class="pure-form" enctype='multipart/form-data' action="{% url 'admin:update_product' product.pk %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="pure-button pure-button-primary" type="submit" value="Сохранить">
</form>
{% endblock %}

geekshop/adminapp/templates/adminapp/update_user.html
{% extends 'adminapp/base.html' %}

{% block content %}
{% if user.image %}
    <img class="user-image" src="{{ user.image.url }}"/>
{% endif %}

<form class="pure-form" enctype='multipart/form-data' action="{% url 'admin:update_user' object.pk %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="pure-button pure-button-primary" type="submit" value="Сохранить">
</form>
{% endblock %}

geekshop/adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% block content %}
<div class="create-button">
    <a href="{% url 'admin:create_user' %}" class="pure-button pure-button-primary">
        Создать пользователя
    </a>
</div>
<table class="pure-table">
    <thead>
        <tr>
            <th>Username</th>
            <th>City</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for user in object_list %}
        <tr class="{% if not user.is_active %} inactive {% endif %}">
            <td>{{ user.username }}</td>
            <td>{{ user.city }}</td>
            <td>
                <a href="{% url 'admin:update_user' user.pk %}" class="pure-button pure-button-primary">
                    редактировать
                </a>
            </td>
            <td>
                <a href="{% url 'admin:delete_user' user.pk %}" class="pure-button pure-button-primary">
                удалить
                </a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}